export { default as Navbar} from "./Navbar"
export { default as About} from "./About"
export { default as Aboutme} from "./Aboutme"
export { default as Works} from "./Works"
export { default as Contact} from "./Contact"
export { default as Footer} from "./Footer"
export { default as Testimonial} from "./Testimonial"